//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAA.Web.Resources.HR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAA.Web.Resources.HR.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been Activated successfully.
        /// </summary>
        public static string ActivateMessage {
            get {
                return ResourceManager.GetString("ActivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Employee.
        /// </summary>
        public static string ActiveEmp {
            get {
                return ResourceManager.GetString("ActiveEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been Added.
        /// </summary>
        public static string AddMessage {
            get {
                return ResourceManager.GetString("AddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Employee.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allownce1.
        /// </summary>
        public static string Allow1 {
            get {
                return ResourceManager.GetString("Allow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allownce2.
        /// </summary>
        public static string Allow2 {
            get {
                return ResourceManager.GetString("Allow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allownce3.
        /// </summary>
        public static string Allow3 {
            get {
                return ResourceManager.GetString("Allow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allownce4.
        /// </summary>
        public static string Allow4 {
            get {
                return ResourceManager.GetString("Allow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allownce5.
        /// </summary>
        public static string Allow5 {
            get {
                return ResourceManager.GetString("Allow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        public static string BasicSal {
            get {
                return ResourceManager.GetString("BasicSal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Employee.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Changes.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been Deactivated successfully.
        /// </summary>
        public static string DeactivateMessage {
            get {
                return ResourceManager.GetString("DeactivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Employee.
        /// </summary>
        public static string DeactiveEmp {
            get {
                return ResourceManager.GetString("DeactiveEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction1.
        /// </summary>
        public static string Deduc1 {
            get {
                return ResourceManager.GetString("Deduc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction2.
        /// </summary>
        public static string Deduc2 {
            get {
                return ResourceManager.GetString("Deduc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string EmpJobTitle {
            get {
                return ResourceManager.GetString("EmpJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Job ID.
        /// </summary>
        public static string EmployeeJobId {
            get {
                return ResourceManager.GetString("EmployeeJobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees&apos; List.
        /// </summary>
        public static string Employeelist {
            get {
                return ResourceManager.GetString("Employeelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Information.
        /// </summary>
        public static string ExtraInfo {
            get {
                return ResourceManager.GetString("ExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name arabic.
        /// </summary>
        public static string FirstNameA {
            get {
                return ResourceManager.GetString("FirstNameA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqama Expiry Date Or National ID Expiry Date.
        /// </summary>
        public static string IqamaExpiryDate {
            get {
                return ResourceManager.GetString("IqamaExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqama Number Or National ID Number.
        /// </summary>
        public static string IqamaNo {
            get {
                return ResourceManager.GetString("IqamaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Id.
        /// </summary>
        public static string JobId {
            get {
                return ResourceManager.GetString("JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name arabic.
        /// </summary>
        public static string LastNameA {
            get {
                return ResourceManager.GetString("LastNameA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStat {
            get {
                return ResourceManager.GetString("MaritalStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name arabic.
        /// </summary>
        public static string MiddleNameA {
            get {
                return ResourceManager.GetString("MiddleNameA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobNumber {
            get {
                return ResourceManager.GetString("MobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameIndex {
            get {
                return ResourceManager.GetString("NameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiry Date.
        /// </summary>
        public static string PassExpiryDate {
            get {
                return ResourceManager.GetString("PassExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Id.
        /// </summary>
        public static string PassId {
            get {
                return ResourceManager.GetString("PassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in Saving Employee.
        /// </summary>
        public static string ProblemSaving {
            get {
                return ResourceManager.GetString("ProblemSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Addition.
        /// </summary>
        public static string PTAdd {
            get {
                return ResourceManager.GetString("PTAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s List.
        /// </summary>
        public static string PTList {
            get {
                return ResourceManager.GetString("PTList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string PTProfile {
            get {
                return ResourceManager.GetString("PTProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request History.
        /// </summary>
        public static string ReqHistory {
            get {
                return ResourceManager.GetString("ReqHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been Updated.
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
    }
}
