//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPAA.Web.Resources.HR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Request {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Request() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPAA.Web.Resources.HR.Request", typeof(Request).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Request.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Request.
        /// </summary>
        public static string CreateRequest {
            get {
                return ResourceManager.GetString("CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string DeclineBtn {
            get {
                return ResourceManager.GetString("DeclineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        public static string EmployeeJobId {
            get {
                return ResourceManager.GetString("EmployeeJobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Installment Date.
        /// </summary>
        public static string FirstInstallmentDate {
            get {
                return ResourceManager.GetString("FirstInstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Istallment.
        /// </summary>
        public static string InstallmentAmount {
            get {
                return ResourceManager.GetString("InstallmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request List.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Installment Date.
        /// </summary>
        public static string LastInstallmentDate {
            get {
                return ResourceManager.GetString("LastInstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Amount.
        /// </summary>
        public static string LoanAmount {
            get {
                return ResourceManager.GetString("LoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Date (Gregorian).
        /// </summary>
        public static string LoanDateGr {
            get {
                return ResourceManager.GetString("LoanDateGr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Date (Hijri).
        /// </summary>
        public static string LoanDateHj {
            get {
                return ResourceManager.GetString("LoanDateHj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monetary.
        /// </summary>
        public static string Monetary {
            get {
                return ResourceManager.GetString("Monetary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For How Many Months.
        /// </summary>
        public static string NumberOfMonths {
            get {
                return ResourceManager.GetString("NumberOfMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replied.
        /// </summary>
        public static string Replied {
            get {
                return ResourceManager.GetString("Replied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string ReplyBtn {
            get {
                return ResourceManager.GetString("ReplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Description.
        /// </summary>
        public static string ReplyDesc {
            get {
                return ResourceManager.GetString("ReplyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been accepted, now you are unable to make changes in this request..
        /// </summary>
        public static string RequestAccepted {
            get {
                return ResourceManager.GetString("RequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been created..
        /// </summary>
        public static string RequestCreated {
            get {
                return ResourceManager.GetString("RequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been deleted..
        /// </summary>
        public static string RequestDeleted {
            get {
                return ResourceManager.GetString("RequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RequestDesc {
            get {
                return ResourceManager.GetString("RequestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been replied..
        /// </summary>
        public static string RequestReplied {
            get {
                return ResourceManager.GetString("RequestReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Reply.
        /// </summary>
        public static string RequestReply {
            get {
                return ResourceManager.GetString("RequestReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string RequestTopic {
            get {
                return ResourceManager.GetString("RequestTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Detail.
        /// </summary>
        public static string UpdatePageTitle {
            get {
                return ResourceManager.GetString("UpdatePageTitle", resourceCulture);
            }
        }
    }
}
